version: '2.1'
services:
    app:
      build: ./app
      ports:
        - 8081:8080
      links:
        - db
      volumes:
        - app-data:/opt/molgenis
      labels:
        io.rancher.container.create_agent: 'true'
        io.rancher.scheduler.global: 'true'
    db:
      build: ./db
      expose:
        - 5432
      volumes:
        - db-data:/var/lib/postgresql/data
      labels:
        io.rancher.container.create_agent: 'true'
volumes:
    db-data:
    app-data:
