app:
  image: registry.haakma.org/molgenis:4.1.0
  ports:
    - 8081:8080
  links:
    - db
  volumes_from:
    - molgenis-data
  labels:
    io.rancher.sidekicks: molgenis-data
    io.rancher.scheduler.affinity:host_label: type=molgenis
    io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
    expose:
      - 5432
     volumes_from:
      - postgres-data
    labels:
      io.rancher.sidekicks: postgres-data
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis

 postgres-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
    volumes:
      - /var/lib/postgresql/data/pgdata
  molgenis-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
    volumes:
      - /opt/molgenis