  molgenis:
    image: registry.haakma.org/molgenis:5.0
    ports:
      - 8081:8080
    links:
      - postgres
      - elasticsearch
    volumes_from:
      - molgenis-data
    labels:
      io.rancher.sidekicks: molgenis-data
      io.rancher.scheduler.affinity:host_label: type=molgenis
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes_from:
      - postgres-data
    expose:
      - 5432
    labels:
      io.rancher.sidekicks: postgres-data
      io.rancher.scheduler.affinity:host_label: type=molgenis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=molgenis
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes_from:
      - elasticsearch-data
    ports:
      - 9200:9200
      - 9300:9300
    labels:
      io.rancher.sidekicks: elasticsearch-data
      io.rancher.scheduler.affinity:host_label: type=molgenis
  postgres-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
    volumes:
      - /var/lib/postgresql/data/pgdata
  molgenis-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
    volumes:
      - /opt/molgenis
  elasticsearch-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
    volumes:
      - /usr/share/elasticsearch/data
