  molgenis:
    image: sidohaakma/molgenis-docker:5.0.1
    ports:
      - 8081:8080
    links:
      - postgres
      - elasticsearch
    volumes_from:
      - molgenis-data
    labels:
      io.rancher.sidekicks: molgenis-data
      io.rancher.scheduler.global: true
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=molgenis
      - POSTGRES_PASSWORD=molgenis
      - POSTGRES_DB=molgenis
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes_from:
      - postgres-data
    expose:
      - 5432
    labels:
      io.rancher.sidekicks: postgres-data
      io.rancher.scheduler.global: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=molgenis
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes_from:
      - elasticsearch-data
    ports:
      - 9200
      - 9300
    labels:
      io.rancher.sidekicks: elasticsearch-data
      io.rancher.scheduler.global: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
  loadbalancer:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
      - 80
    labels:
      io.rancher.scheduler.global: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis

  postgres-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
    volumes:
      - /var/lib/postgresql/data/pgdata
  molgenis-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
    volumes:
      - /opt/molgenis
  elasticsearch-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
      io.rancher.scheduler.affinity:host_label: type=molgenis
      io.rancher.scheduler.affinity:container_label: io.rancher.stack.name=molgenis
    volumes:
      - /usr/share/elasticsearch/data
