.catalog:
  name: molgenis
  version: v5.0.0
  description: Molgenis
  minimum_rancher_version: v1.6.3
loadbalancer:
  scale: 1
  lb_config:
    port_rules:
    - source_port: 80
      target_port: 8081
      service: molgenis
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000