name: Molgenis
description: Molgenis | Flexible software for scientific data
version: v5.0.0
category: All
support: Molgenis DEV-teams
maintainer: Molgenis DEV-team and community-members
projectURL: http://molgenis.org